batch: add a target_end_at of parameter
maiha/adgen.cr pull request #2
Opened 2022-09-08 06:00 UTC by norihito-sato-ss

2022-09-08 06:59 UTC, maiha requested changes

2022-09-08 06:59 UTC, maiha commented on shard.yml
> +    version: 1.1.2
version指定良いですね。
固定だと「自動アップグレード」や「他shardとの連携」に難があるので、以上(`>=`)にしておく方が安全そうです。

```suggestion
    version: ">= 1.1.2"
```

2022-09-08 06:59 UTC, maiha commented on src/cli/cmds/batch/recv_publisher.cr
> +      if /-d target_end_at=/.match(config.api_cmd?(name).to_s)
if条件の対象は
❌ `api_cmd`
✅ `batch_target_end_at`
がよいです。

例えば、
```toml
cmd = "/api/v2/marketech/native_pure_ads -d target_end_at=today"
```

のように直接埋め込んだ場合に、`batch_target_end_at` の値を読み込もうとするのは変な感じがするので。

逆に、`{TARGET_END_AT}` パラメータがcmd中に存在しない場合でも、configに`batch_target_end_at` がある場合は、paramsに追加されてしまうので、`ParamsCmd` の parameter mismatch を良きに修正する必要はあります。
* 「パラメータ完全一致」→「必要なパラメータがあればよい」

2022-09-08 06:59 UTC, maiha commented on src/cli/cmds/batch/recv_publisher.cr
> +      recv_publisher_impl(name, label, room, parser, publisher_id, i, target_end_at)
後方互換的に、configのtarget_end_at定義が不要なケースもあるので(詳細は後述)、最初に渡すのでなく、必要な時点まで待ってlazyに読み込む方が良いです。

2022-09-08 07:56 UTC, norihito-sato-ss commented on shard.yml
> +    version: 1.1.2
ありがとうございます。

2022-09-08 08:12 UTC, norihito-sato-ss commented on src/cli/cmds/batch/recv_publisher.cr
> +      if /-d target_end_at=/.match(config.api_cmd?(name).to_s)
確かに！修正します。

2022-09-08 09:27 UTC, norihito-sato-ss commented on src/cli/cmds/batch/recv_publisher.cr
> +      recv_publisher_impl(name, label, room, parser, publisher_id, i, target_end_at)
なるほど！確かに。修正してみます。

2022-09-08 09:35 UTC, maiha commented on src/cli/cmds/batch/recv_publisher.cr
> +      if /-d target_end_at=/.match(config.api_cmd?(name).to_s)
そう考えると、
* `api_cmd` に `{TARGET_END_AT}` があるかどうか

を見るのが一番正しい気がしてきた。

2022-09-08 11:59 UTC, maiha requested changes
あと、全体的にtypoがコピペされちゃってる感じです
```diff
- "TARGET_EMD_AT"
+ "TARGET_END_AT"
```

2022-09-08 11:59 UTC, maiha commented on src/cli/adgen/config.cr
> +  def batch_target_end_at? : String?
strマクロが同じものを作ってくれるので、ここの修正は不要です。(strマクロでOKです)

2022-09-08 11:59 UTC, maiha commented on src/cli/cmds/batch/recv_publisher.cr
> +      if batch_target_end_at = config.batch_target_end_at?
if条件は、

* 設定があるか(config.batch_target_end_at?)

ではなく
* cmdに該当パラメータがあるか

で判定したいです。

それにより、設定を読む条件に過不足ないため、
* 設定がなければエラーにできる (`batch_target_end_at?`→`batch_target_end_at`)
* 設定値のミスはエラーにできる(`Pretty::Date.parse?`→`Pretty::Date.parse`)
* 正しく日付に変換する(`to_s("%F")`)

あたりを加味すると、以下のようなコードにできそうです。

```crystal
if config.api_cmd?(name).to_s.includes?("{TARGET_END_AT}")
  params["TARGET_END_AT"] = Pretty::Date.parse(config.batch_target_end_at).to_s("%F")
end
```

2022-09-08 11:59 UTC, maiha commented on src/cli/cmds/batch/url_builder.cr
> +    if !/\{TARGET_EMD_AT\}/.match(config.api_cmd?(name).to_s)
ここは不要になります。
（↑で必要な場合だけ設定するようにしたので）

2022-09-09 00:07 UTC, norihito-sato-ss commented on src/cli/cmds/batch/url_builder.cr
> +    if !/\{TARGET_EMD_AT\}/.match(config.api_cmd?(name).to_s)
ありがとうございます。:pray:
修正します。

2022-09-09 00:09 UTC, norihito-sato-ss commented on src/cli/cmds/batch/recv_publisher.cr
> +      if batch_target_end_at = config.batch_target_end_at?
ありがとうございます。:pray:
修正します。

2022-09-09 00:15 UTC, norihito-sato-ss commented on src/cli/adgen/config.cr
> +  def batch_target_end_at? : String?
承知しました。
typo 気がつきませんでした。:sweat_drops:
ありがとうございます。:pray:

2022-09-09 03:17 UTC, maiha approved these changes
👍

2022-09-09 03:18 UTC, merged